version: '3'
services:
  mongoDB:
    image: mongo:4.4.19-rc0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./mongo_data:/data/db
  ETCD:
    image: bitnami/etcd:3
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_INITIAL_CLUSTER=node1: http://0.0.0.0:2380
      ETCD_NAME: node1
      ETCD_DATA_DIR: /opt/bitnami/etcd/data
    volumes:
      - ./etcd/data:/opt/bitnami/etcd/data
    networks:
      - etcdnet

networks:
  etcdnet:
    name: etcdnet

